=== InvertedLogic/Team-Blauge/src/XML/projectlist_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="projects">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="project" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"></xs:element>
							<xs:element name="lastmod" type="xs:dateTime"></xs:element>
							<xs:element name="description" type="xs:string"></xs:element>
							<xs:element name="key" type="xs:string"></xs:element>
							<xs:element name="userlist">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="user" maxOccurs="unbounded" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="projectname" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="count" type="xs:int"></xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== InvertedLogic/Team-Blauge/src/XML/projectlist_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<projects count="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projectlist_schema.xsd">
  <project projectname="">
    <name>name</name>
    <lastmod>2001-12-31T12:00:00</lastmod>
    <description>description</description>
    <key>key</key>
    <userlist>
      <user>user</user>
    </userlist>
  </project>
</projects>
