=== InvertedLogic/Team-Blauge/src/XML/server_projectlist_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="projectlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="project" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="projectname"/>
              <xs:element type="xs:dateTime" name="lastmod"/>
              <xs:element type="xs:string" name="description"/>
              <xs:element type="xs:string" name="key"/>
              <xs:element name="userlist">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:boolean" name="isAdmin" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="count" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:int" name="count"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== InvertedLogic/Team-Blauge/src/XML/files/projectlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<projectlist count="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="server_projectlist_schema.xsd">
  <projectOverview ID="2">
    <projectname>projectname</projectname>
    <lastmod>2001-12-31T12:00:00</lastmod>
    <description>description</description>
    <key>key</key>
    <userlist count="0">
      <user Admin="true">user</user>
    </userlist>
  </projectOverview>
    <projectOverview ID="2">
    <projectname>projectname</projectname>
    <lastmod>2001-12-31T12:00:00</lastmod>
    <description>description</description>
    <key>key</key>
    <userlist count="0">
      <user Admin="true">user</user>
    </userlist>
  </projectOverview>
</projectlist>
